spring:
    profiles:
        include: domain, infra, security    # 활성화할 추가 프로파일 설정
        active: local                       # 활성화할 프로파일 지정

server:
    port: 8081                              # 8081 포트 사용
    servlet:
        context-path: /v1                   # 모든 요청이 '/v1' 경로로 시작